Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'attendees/new'
  get 'attendees/create'
  get 'attendees/edit'
  get 'attendees/update'
  get 'attendees/destroy'
  get 'photographers/new'
  get 'photographers/create'
  get 'photographers/edit'
  get 'photographers/update'
  get 'photographers/destroy'
  get 'bookings/show'
  get 'bookings/create'
  get 'bookings/destroy'
  get 'packages/index'
  get 'packages/show'
  get 'available_photographers/create'
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
